In [155]:
import pandas as pd
prices = pd.read_csv("prices.csv")
prices.head()

/var/folders/3r/ygns0_h16pl1__pln5g3j8t80000gp/T/ipykernel_86245/2165428866.py:2: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  prices = pd.read_csv("prices.csv")

,file_id,chainid,subchainid,storeid,bikoretno,priceupdatedate,itemcode,itemname,manufacturername,manufacturecountry,...,bisweighted,qtyinpackage,itemprice,unitofmeasureprice,allowdiscount,itemstatus,itemid,itemtype,lastupdatedate,lastupdatetime
0,samples_price/Super-Pharm/Price7290172900007-0...,7290172900007,100,13,100,2022-10-20,7298171183957,שמיכת פלנל פרווה 185/125 עיצוב מיקי מאוס,לייף,NO-CONTENT,...,0,1.00,39.9,0.0,1,0,not_apply,not_apply,unknown,unknown
1,samples_price/Super-Pharm/Price7290172900007-0...,7290172900007,100,33,100,2022-10-20,7298171183957,שמיכת פלנל פרווה 185/125 עיצוב מיקי מאוס,לייף,NO-CONTENT,...,0,1.00,44.9,0.0,1,0,not_apply,not_apply,unknown,unknown
2,samples_price/Super-Pharm/Price7290172900007-0...,7290172900007,100,36,100,2022-10-20,46214731552,עוגיות שוקולד ציפס 225 גרם,שסטוביץ,NO-CONTENT,...,0,1.00,12.9,0.0,1,0,not_apply,not_apply,unknown,unknown
3,samples_price/Super-Pharm/Price7290172900007-0...,7290172900007,100,36,100,2022-10-20,8710502194801,עוגיות שוקולד ציפס עם פירות יער 175 גרם,שסטוביץ,הולנד,...,0,1.00,12.9,0.0,1,0,not_apply,not_apply,unknown,unknown
4,samples_price/Super-Pharm/Price7290172900007-0...,7290172900007,100,12,100,2022-10-20,7290004078225,פלאקס מי פה 500 ירוק,General,NO-CONTENT,...,0,1.00,36.9,0.0,1,0,not_apply,not_apply,unknown,unknown

In [156]:
prices.columns

Index(['file_id', 'chainid', 'subchainid', 'storeid', 'bikoretno',
       'priceupdatedate', 'itemcode', 'itemname', 'manufacturername',
       'manufacturecountry', 'manufactureritemdescription', 'unitqty',
       'quantity', 'unitofmeasure', 'bisweighted', 'qtyinpackage', 'itemprice',
       'unitofmeasureprice', 'allowdiscount', 'itemstatus', 'itemid',
       'itemtype', 'lastupdatedate', 'lastupdatetime'],
      dtype='object')

In [157]:
manufacturing_columns = ['manufacturername','manufacturecountry', 'manufactureritemdescription']
units_columns = ['unitqty','unitofmeasure','unitofmeasure','unitofmeasureprice','qtyinpackage']
date_columns = ['lastupdatedate', 'lastupdatetime','priceupdatedate']
item_columns = ['itemname','itemcode','itemid']

## 'unitqty','unitofmeasure','unitofmeasure','unitofmeasureprice','itemprice','itemname','qtyinpackage'

In [158]:
prices[['unitqty','unitofmeasure','unitofmeasure','unitofmeasureprice','itemprice','itemname','qtyinpackage']]

,unitqty,unitofmeasure,unitofmeasure,unitofmeasureprice,itemprice,itemname,qtyinpackage
0,NO-CONTENT,0.00,0.00,0.0000,39.9,שמיכת פלנל פרווה 185/125 עיצוב מיקי מאוס,1.00
1,NO-CONTENT,0.00,0.00,0.0000,44.9,שמיכת פלנל פרווה 185/125 עיצוב מיקי מאוס,1.00
2,גרם,100.00,100.00,0.0000,12.9,עוגיות שוקולד ציפס 225 גרם,1.00
3,NO-CONTENT,100.00,100.00,0.0000,12.9,עוגיות שוקולד ציפס עם פירות יער 175 גרם,1.00
4,"מ""ל",100.00,100.00,0.0000,36.9,פלאקס מי פה 500 ירוק,1.00
...,...,...,...,...,...,...,...
85331,Unknown,Unknown,Unknown,0.0000,23.9,פותח סתימות נוזל,1
85332,גרמים,100 גרם,100 גרם,19.9000,19.9,קפה אספרסו 100 גר,1
85333,גרמים,100 גרם,100 גרם,3.4500,6.9,טורטינה חלב 200 גר,1
85334,גרמים,100 גרם,100 גרם,9.9667,29.9,שרימפס טמפורה 300 גר,1
85335,מיליליטרים,"100 מ""ל","100 מ""ל",4.1754,11.9,רוטב לסלט בסגנון אסי,1

In [159]:
def warp_float(x):
    try:
        return float(x)
    except ValueError:
        return x

prices['qtyinpackage'] = prices['qtyinpackage'].apply(warp_float)

In [160]:
prices[prices['qtyinpackage'].apply(lambda x:isinstance(x,str))]['qtyinpackage'].unique()

array(['לא ידוע'], dtype=object)

In [174]:
unique_qty = prices.groupby('itemcode').apply(lambda x:x['qtyinpackage'].unique()).reset_index(name="unique_qty")
unique_qty[unique_qty.unique_qty.apply(len)>1]
# why so? i would assume all as one number and לא ידוע

            itemcode            unique_qty
0                  1          [0.0, 500.0]
13                25            [0.0, 6.0]
29               101  [0.0, 12.0, לא ידוע]
38               110            [0.0, 1.0]
40               112            [0.0, 1.0]
...              ...                   ...
18862  9310072028750           [24.0, 0.0]
18868  9322969000015   [0.0, לא ידוע, 1.0]
18869  9322969000022        [לא ידוע, 0.0]
18870  9322969000039            [0.0, 1.0]
18871  9322969000046   [0.0, לא ידוע, 1.0]

[5440 rows x 2 columns]

In [ ]:
# maybe '0' is ״לא יודע״

In [178]:
prices[prices['itemcode'] == 9322969000022]

,file_id,chainid,subchainid,storeid,bikoretno,priceupdatedate,itemcode,itemname,manufacturername,manufacturecountry,...,bisweighted,qtyinpackage,itemprice,unitofmeasureprice,allowdiscount,itemstatus,itemid,itemtype,lastupdatedate,lastupdatetime
559,samples_price/Rami Levy/Price7290058140886-002...,7290058140886,1,2,1,2020-10-12 10:14:48,9322969000022,פריכיות תירס עם סויה,Algam Gil - Agent,ישראל,...,0,לא ידוע,11.9,0.0793,1,1,1046332,1,unknown,unknown
1838,samples_price/Rami Levy/Price7290058140886-002...,7290058140886,1,2,1,2020-10-12 10:14:48,9322969000022,פריכיות תירס עם סויה,Algam Gil - Agent,ישראל,...,0,לא ידוע,11.9,0.0793,1,1,1046332,1,unknown,unknown
59240,samples_price/SuperYuda/Price7290058198450-035...,7290058198450,1,35,9,2022-10-20 14:48:00,9322969000022,"ריל פוד פריכיות תירס עם סויה וזרעי פשתן, ללא ג...",לא ידוע,לא ידוע,...,0,0.0,13.9,13.9000,0,1,not_apply,1,unknown,unknown

In [ ]:
9310072028750

In [153]:
mapping = {
    'מ"ל':"מיליליטר",
    "יח'":"יחידה",
    "'יח":"יחידה",
    "יח":"יחידה",
    "יח`":"יחידה",
    'י"ח':"יחידה",
    "יחידו":"יחידות",
    "יחדה":"יחידה",
     "ליח":"יחידה",
    "יחידות":"יחידה",
    "ליחידה":"יחידה",
    "פריט":"יחידה",

    'ק"ג':"קילוגרמים",
    "קילו":"קילוגרמים",
    "לקג":"קילוגרמים",
    "ק''ג":"קילוגרמים",
    "קג":"קילוגרמים",
    "קילוג":"קילוגרמים",

    "גרם":"גרמים",
    
    "מל":"מיליליטר",
    "ליטור":"ליטרים",
    "ליטרים":"ליטרים",
}

# first mapping
prices['unitqty'] = prices['unitqty'].apply(lambda x: mapping[x] if x in mapping else x)

In [150]:
def has_numbers(inputString):
    return any(char.isdigit() for char in inputString)

with_number = prices[prices['unitqty'].apply(has_numbers)][['unitqty','unitofmeasure']]
(with_number['unitqty'] == with_number['unitofmeasure']).all() # we can remove letters from unitofmeasure and numbers from unitqty

True

In [151]:
import re 
prices['unitqty'] = prices['unitqty'].apply(lambda x:re.sub(r'[^א-ת-A-Za-z]+', '', x)).apply(lambda x: mapping[x] if x in mapping else x)

In [152]:
prices['unitqty'].value_counts().index

Index(['יחידה', '', 'גרמים', 'מיליליטרים', 'קילוגרמים', 'לאידוע', 'ליטרים',
       'Unknown', 'מארז', 'מטרים', 'NO-CONTENT', 'מיליליטר', 'אורך', 'קרטון',
       ' ליטרים'],
      dtype='object')

In [114]:
needed_explaing = ["Unknown","NO-CONTENT",'Unknown','']
prices[prices['unitqty'].isin(needed_explaing)][['file_id','itemname','unitqty','unitofmeasure']]

,file_id,itemname,unitqty,unitofmeasure
0,samples_price/Super-Pharm/Price7290172900007-0...,שמיכת פלנל פרווה 185/125 עיצוב מיקי מאוס,NO-CONTENT,0.00
1,samples_price/Super-Pharm/Price7290172900007-0...,שמיכת פלנל פרווה 185/125 עיצוב מיקי מאוס,NO-CONTENT,0.00
3,samples_price/Super-Pharm/Price7290172900007-0...,עוגיות שוקולד ציפס עם פירות יער 175 גרם,NO-CONTENT,100.00
8,samples_price/Super-Pharm/Price7290172900007-0...,פלמוליב נוזל כלים 750 קלאסי ירוק,NO-CONTENT,100.00
10,samples_price/Super-Pharm/Price7290172900007-0...,פלמוליב ס.נוזלי 750 מל חלב ודבש משאבה,NO-CONTENT,100.00
...,...,...,...,...
85319,samples_price/Keshet Taamim/Price7290785400000...,קופון ציפר,Unknown,Unknown
85322,samples_price/Keshet Taamim/Price7290785400000...,צוואר עוף למילוי,Unknown,Unknown
85324,samples_price/Keshet Taamim/Price7290785400000...,צמרוני ביוטי עגול 20,Unknown,Unknown
85327,samples_price/Keshet Taamim/Price7290785400000...,כריות יפניות אלפא,Unknown,Unknown
85331,samples_price/Keshet Taamim/Price7290785400000...,פותח סתימות נוזל,Unknown,Unknown

In [42]:
import re
# .apply(lambda x:re.sub(r'[^א-ת-A-Za-z0-9-.]+', '', x))
prices['unitofmeasure'].value_counts().index

Index(['יחידה', '00000', '100 גרם', '100 מ"ל', 'יחידה   ', 'ק"ג  ', 'ק"ג',
       'ליטר    ', 'יח'', 'מארז ', 'Unknown ', 'ק"ג     ', 'פריט    ',
       'NO-CONTENT', 'ליטר', '100 מ'ל', 'קילוג', '100.00', 'יח   ',
       'ל-100 גרם', 'ל  גרם', 'ל-100 מ"ל', 'גרם  ', 'יחדה ', 'מטר', '100 ליטר',
       'מ"ל', '80  גרם', '1 ליטר', 'יח', 'גרם', 'י"ח', '100 מל', 'Unknown',
       'ארגז', 'ל יח`', 'יח'  ', 'ל  מ"ל', 'יח`', 'גרם     ', '100 קילו',
       ''יח', '100 יחידה', '100 י"ח', '56  יח'', '100 ק"ג', 'קילו', 'לא ידוע',
       '0.00', 'אורך', '100 יח'', '100 קג', '100 0', '100 קרטון', '10  יח'',
       '100 לק"ג', '100 יח', 'יחידו', '200 יח'', '2   יח'', 'קג   ', '100 לקג',
       '100 ליטור', 'ק''ג ', 'לקג', 'לליטר', '3   יח'', '6   יח''],
      dtype='object')

In [ ]:
# look into 'itemprice'
prices['itemprice'].isna().any()

False

:

In [ ]:
prices['itemprice'].describe()

count    85336.000000
mean        17.845189
std         21.548643
min          0.010000
25%          7.900000
50%         12.900000
75%         19.900000
max        799.000000
Name: itemprice, dtype: float64

:

In [ ]:
prices[prices['itemprice'] == 0.1]
# this can be a benckmark to clustering the items. we hope the cluster with place all of those togatuer.

,file_id,chainid,subchainid,storeid,bikoretno,priceupdatedate,itemcode,itemname,manufacturername,manufacturecountry,...,bisweighted,qtyinpackage,itemprice,unitofmeasureprice,allowdiscount,itemstatus,itemid,itemtype,lastupdatedate,lastupdatetime
8601,samples_price/ShefaBarcartAshem/Price729005813...,7290058134977,1,41,6,2022-10-20 17:52:00,1138,מחיר כללי 10 אג',לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
8608,samples_price/ShefaBarcartAshem/Price729005813...,7290058134977,1,41,6,2022-10-20 17:52:00,11004,שקית קופה 10 אגורות,לא ידוע,לא ידוע,...,0,3000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
12570,samples_price/ShefaBarcartAshem/Price729005813...,7290058134977,1,23,9,2022-10-20 17:57:00,1138,מחיר כללי 10 אג',לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
12579,samples_price/ShefaBarcartAshem/Price729005813...,7290058134977,1,23,9,2022-10-20 17:57:00,11004,שקית קופה 10 אגורות,לא ידוע,לא ידוע,...,0,3000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
19396,samples_price/ZolVeBegadol/Price7290058173198-...,7290058173198,1,37,9,2022-10-20 17:27:00,2291,שקיות ניילון זול ובגדול,לא ידוע,לא ידוע,...,0,2000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
25075,samples_price/ZolVeBegadol/Price7290058173198-...,7290058173198,1,36,4,2022-10-20 17:12:00,2291,שקיות ניילון זול ובגדול,לא ידוע,לא ידוע,...,0,2000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
39646,samples_price/King Store/Price7290058108879-33...,7290058108879,1,335,3,2022-10-20 17:06:00,555444,שקית קופה,לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
42167,samples_price/King Store/Price7290058108879-01...,7290058108879,1,18,7,2022-10-20 17:54:00,555444,שקית קופה,לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
44533,samples_price/King Store/Price7290058108879-33...,7290058108879,1,336,0,2022-10-20 17:26:00,555444,שקית קופה,לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
54335,samples_price/SuperYuda/Price7290058198450-036...,7290058198450,1,36,2,2022-10-20 13:09:00,1222,"שקית ניילון ""סופר יודה""",לא ידוע,לא ידוע,...,0,3000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
56383,samples_price/SuperYuda/Price7290058198450-035...,7290058198450,1,35,9,2022-10-20 14:48:00,1222,"שקית ניילון ""סופר יודה""",לא ידוע,לא ידוע,...,0,3000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
60978,samples_price/SuperYuda/Price7290058198450-038...,7290058198450,1,38,1,2022-10-20 13:02:00,1222,"שקית ניילון ""סופר יודה""",לא ידוע,לא ידוע,...,0,3000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
62869,samples_price/SuperYuda/Price7290058198450-033...,7290058198450,1,33,9,2022-10-20 13:11:00,1222,"שקית ניילון ""סופר יודה""",לא ידוע,לא ידוע,...,0,3000.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
67744,samples_price/Maayan2000/Price7290058159628-04...,7290058159628,1,41,4,2022-10-20 17:24:00,488,שקיות נשיאה,לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown
73625,samples_price/Maayan2000/Price7290058159628-04...,7290058159628,1,48,1,2022-10-20 17:11:00,488,שקיות נשיאה,לא ידוע,לא ידוע,...,0,0.0000,0.1,0.1,0,1,not_apply,1,unknown,unknown

:

In [ ]:
prices[prices['itemprice'] == 799.000000]

,file_id,chainid,subchainid,storeid,bikoretno,priceupdatedate,itemcode,itemname,manufacturername,manufacturecountry,...,bisweighted,qtyinpackage,itemprice,unitofmeasureprice,allowdiscount,itemstatus,itemid,itemtype,lastupdatedate,lastupdatetime
32725,samples_price/GoodPharm/Price7290058197699-909...,7290058197699,1,909,7,2022-10-20 17:59:00,3145891071900,"בלו דה שאנל פיור פרפיום לגבר 150 מ""ל- שאנל",לא ידוע,לא ידוע,...,0,0.0000,799.0,799.0,0,1,not_apply,1,unknown,unknown

:

,file_id,chainid,subchainid,storeid,bikoretno,priceupdatedate,itemcode,itemname,manufacturername,manufacturecountry,...,bisweighted,qtyinpackage,itemprice,unitofmeasureprice,allowdiscount,itemstatus,itemid,itemtype,lastupdatedate,lastupdatetime
39628,samples_price/King Store/Price7290058108879-33...,7290058108879,1,335,3,2022-10-20 17:06:00,334017,תה,לא ידוע,לא ידוע,...,0,0.0000,5.0,5.0,0,1,not_apply,1,unknown,unknown

:

0        he
1        he
2        he
3        he
4        he
         ..
85331    he
85332    he
85333    he
85334    he
85335    he
Name: itemname_lang, Length: 85336, dtype: object

:

array(['מרלו imperial', 'K-333', 'muller simply fruit 1.5% מנגו',
       'מרלו imperial', 'עט cello rainbw כחול 1/20',
       'עט cello butterfion 0.7 סט 3 כחול',
       'עט cello butterfion 0.7 סט 3 מעורב', 'K-300', '7290109580159',
       '7290109580166', '7290109580104', '2198048', 'K-300', 'K-2000',
       'K-333', 'K-4000', 'שטיפת פה shocking fresh',
       'protective salt שטיפת פה', 'לובן צח  white bright',
       'דאב ת.רחצה 500 invigorating ritual', '7290109580159',
       '7290109580166', '2198048', '7290109580111',
       'Cat. Liquid Liner Waterproof',
       'Cat. All Matt Plus Shine Control Powder 010', 'SETTING BRUSH',
       'MIRACLE POWDER SPONGE',
       'Cat. Liquid Camouflage High Coverage Concealer 036',
       'Cat. Blush Box 025', 'Cat. Matt Pro Ink Liquid Lipstick 050',
       'Cat. Plumping Lip Liner 100', 'Catrice Brow Fix Soap Stylist 010',
       'Catrice Power Full 5 Lip Care 030', 'Catrice Quick Dry Top Coat',
       'Catrice More Than Nude Nail Polish 12',
       'Catrice Vegan Coll. Matt Lipst. 040',
       'Catrice Nail Whitening Base Coat', 'Cat. Allround Concealer',
       'Cat. Sharpener', 'Cat. Liquid Liner',
       'Cat. All Matt Plus Shine Control Powder 010',
       'Cat. All Matt Plus Shine Control Powder 025',
       'ORAL B Cavity Defense Bacterial Fighter 6s (SOFT)',
       'a/z huroof al hub flora', 'COLGATE ZIGZAG+ ANTIBACTERIAL BUY 6',
       'COLGATE 360 VISIBLE WHITE B2G2',
       'COLGATE SLIMSOFT CHARCOAL  BUY 2 GET 2',
       'Cat. Mattlover Lipstick Pen 070', 'YSL LIBRE LE PARFUM S90ML',
       'NATURAL B.W - ROYAL NIGHT (U) EDP 100ML', "R3 PLEASURE 5'S",
       'Cat. Blush Box 050', 'Cat.Lip Glow Glamourizer',
       'Cat. True Skin Hydrating Foundation 010',
       'Cat. True Skin Hydrating Foundation 033',
       'Catrice Brow Fix Soap Stylist 010',
       'Catrice Blush Box Glowing & Multi. 030', 'LATTAFA-YARA-100ML',
       "DUREX REAL FEEL 12'S", 'TRUSSARDI UOMO EDT 100',
       'VERSACE CRYSTAL NOIR EDT VAPO 90ML', 'VIP ROSE EDP 80ML',
       'COLGATE ZIGZAG+ ANTIBACTERIAL BUY 6',
       'COLGATE 360 WHOLEMOUTH CLEAN B2G2',
       'COLGATE 360 VISIBLE WHITE B2G2',
       'COLGATE SLIMSOFT CHARCOAL  BUY 2 GET 2',
       'COLGATE ZIGZAG CHARCOAL BUY4', "R3 PLEASURE 5'S",
       'LATTAFA-FAKHAR LATAFA-WOMEN', 'LATTAFA-YARA-100ML',
       '(A/F LULU 320ML (HAMIDI SERIES', 'VIP ROSE EDP 80ML',
       'COLGATE ZIGZAG+ ANTIBACTERIAL BUY 6',
       'COLGATE ZIGZAG CHARCOAL BUY4',
       'Cat. Liquid Camouflage High Coverage Concealer 036',
       'Cat. Blush Box 025', 'Cat. Matt Pro Ink Liquid Lipstick 030',
       'Cat. Matt Pro Ink Liquid Lipstick 050',
       'Cat. Matt Pro Ink Liquid Lipstick 100',
       'Cat. Plumping Lip Liner 100', 'Catrice Brow Fix Soap Stylist 010',
       'Catrice Power Full 5 Lip Care 030', 'Catrice Quick Dry Top Coat',
       'Catrice More Than Nude Nail Polish 12',
       'Catrice Nail Whitening Base Coat', 'Cat. Allround Concealer',
       'Cat. Sharpener', 'Cat. Liquid Liner',
       'Cat. All Matt Plus Shine Control Powder 010',
       'Cat. All Matt Plus Shine Control Powder 025',
       'ORAL B Cavity Defense Bacterial Fighter 6s (SOFT)',
       'a/z huroof al hub flora', 'COLGATE ZIGZAG+ ANTIBACTERIAL BUY 6',
       'COLGATE 360 VISIBLE WHITE B2G2',
       'COLGATE SLIMSOFT CHARCOAL  BUY 2 GET 2', 'EVERYDAY ESSENTIALS',
       'YSL LIBRE LE PARFUM S90ML', "R3 PLEASURE 5'S",
       'Cat. Blush Box 050',
       'Cat. Brow Definer Brush Pen Longlasting 020',
       'Cat. True Skin Hydrating Foundation 010',
       'Catrice Brow Fix Soap Stylist 010',
       'Catrice 20H Ultra Gel Eye Pencil WP 040',
       'Catrice Blush Box Glowing & Multi. 030',
       'Cat. Liquid Liner Waterproof', 'Cat. Kohl Kajal 140',
       'Cat. All Matt Plus Shine Control Powder 010',
       'Cat. Art Couleurs Eyeshadow 110',
       'ORAL B Sensitive Care 5s (Extra Soft)',
       'TK - NO.10 DESIRE DU COEUR (U) EDP 100ML', 'LATTAFA-YARA-100ML',
       "DUREX REAL FEEL 12'S", 'RSACE BRIGHT CRYSTAL EDT VAPO 90ML',
       'TRUSSARDI UOMO EDT 100', 'VIP ROSE EDP 80ML',
       'COLGATE ZIGZAG+ ANTIBACTERIAL BUY 6',
       'COLGATE 360 WHOLEMOUTH CLEAN B2G2',
       'COLGATE 360 VISIBLE WHITE B2G2',
       'COLGATE SLIMSOFT CHARCOAL  BUY 2 GET 2', "R3 PLEASURE 5'S",
       'YSL LIBRE LE PARFUM S90ML',
       'NATURAL B.W - ROYAL NIGHT (U) EDP 100ML', "R3 PLEASURE 5'S",
       'Cat. Power Plumping Gel Lipstick 040',
       'Cat. Brow Definer Brush Pen Longlasting 020',
       'Cat. True Skin Hydrating Foundation 010',
       'Catrice Energy Boost Serum', 'Catrice Brow Fix Soap Stylist 010',
       'Catrice 20H Ultra Gel Eye Pencil WP 040',
       'Catrice 20H Ultra Gel Eye Pencil WP 050',
       'Catrice Blush Box Glowing & Multi. 030', 'Cat. Kohl Kajal 140',
       'Cat. All Matt Plus Shine Control Powder 010',
       'TK - NO.10 DESIRE DU COEUR (U) EDP 100ML', 'LATTAFA-YARA-100ML',
       '(A/F LULU 320ML (HAMIDI SERIES', "DUREX REAL FEEL 12'S",
       'RSACE BRIGHT CRYSTAL EDT VAPO 90ML', 'VIP ROSE EDP 80ML',
       'COLGATE ZIGZAG+ ANTIBACTERIAL BUY 6',
       'COLGATE 360 WHOLEMOUTH CLEAN B2G2',
       'COLGATE 360 VISIBLE WHITE B2G2', 'COLGATE ZIGZAG CHARCOAL BUY4',
       'dual usb 10.5 w', 'dual usb 10 w', 'wire control adapter cable',
       'multipurpose', 'multipurpose', 'K - 300', 'vanish 1liter',
       'birthday girl נר', 'K - 300', 'K - 300', '333 - k',
       'SUN - MUFIN CORER', 'SUN - MUFIN CORER', 'SUN - MUFIN CORER',
       'SUN - MUFIN CORER', 'SUN - MUFIN CORER',
       'SIMILAC GOLD 2 (LACTOSE)-700 GR', 'SIMILAC ADVANCE PLUS 2-700GR',
       's m k kind sive', '2010'], dtype=object)

:

,file_id,chainid,subchainid,storeid,bikoretno,priceupdatedate,itemcode,itemname,manufacturername,manufacturecountry,...,qtyinpackage,itemprice,unitofmeasureprice,allowdiscount,itemstatus,itemid,itemtype,lastupdatedate,lastupdatetime,itemname_lang
24438,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,2,1,2021-02-18 16:53:41,7290109580159,7290109580159,לא ידוע,לא ידוע,...,לא ידוע,25.9,0.1439,1,1,126469,1,unknown,unknown,None
24439,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,2,1,2021-02-18 16:53:41,7290109580166,7290109580166,לא ידוע,לא ידוע,...,לא ידוע,25.9,0.1727,1,1,126470,1,unknown,unknown,None
24440,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,2,1,2021-02-18 16:53:42,7290109580104,7290109580104,לא ידוע,לא ידוע,...,לא ידוע,25.9,0.1727,1,1,126471,1,unknown,unknown,None
24441,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,2,1,2021-11-02 16:06:42,7290002198048,2198048,לא ידוע,לא ידוע,...,לא ידוע,89.0,89.0000,1,1,126203,1,unknown,unknown,None
30281,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,1,4,2021-02-18 10:35:13,7290109580159,7290109580159,לא ידוע,לא ידוע,...,לא ידוע,25.9,14.3889,1,1,135305,1,unknown,unknown,None
30283,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,1,4,2021-02-18 10:50:13,7290109580166,7290109580166,לא ידוע,לא ידוע,...,לא ידוע,25.9,17.2667,1,1,135306,1,unknown,unknown,None
30285,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,1,4,2021-11-03 09:17:09,7290002198048,2198048,לא ידוע,לא ידוע,...,לא ידוע,89.0,89.0000,1,1,135038,1,unknown,unknown,None
30286,samples_price/Super Dosh/Price7290876100000-00...,7290876100000,1,1,4,2022-01-23 15:05:13,7290109580111,7290109580111,לא ידוע,לא ידוע,...,לא ידוע,25.9,21.5833,1,1,138819,1,unknown,unknown,None
64538,samples_price/SuperYuda/Price7290058198450-033...,7290058198450,1,33,9,2022-10-20 13:11:00,8414775012328,s m k kind sive,לא ידוע,לא ידוע,...,24.0000,10.0,10.0000,0,1,not_apply,1,unknown,unknown,et
77355,samples_price/mahsani a shuk/Price729063380000...,7290633800006,0,263,0,2022/10/20 13:21,8888888888,2010,לפ הוצ בולט תעשיו,NO-CONTENT,...,1,20.1,20.1000,0,1,not_apply,0,NO-CONTENT,NO-CONTENT,None

:

NameError: name 'itemname_anom' is not defined

NameError: name 'prices' is not defined

In [ ]:
# looking into 'itemid'
chanis_with_itemid = prices[prices['itemid'] != "not_apply"]
chanis_with_itemid['chainid'].unique()

array([7290058140886, 7291059100008, 7290725900003, 7290876100000,
       7290103152017, 7291056200008, 7290639000004, 7290803800003,
       7290526500006, 7290055700007, 7290055700014, 7290492000005,
       7290700100008, 7290785400000])

:

In [18]:
chanis_with_itemid.groupby('file_id').apply(lambda x:x['itemid'].unique().shape[0]/x.shape[0]).value_counts()
# the item id is some kind of internal id, not sure what for.

1.0    136
dtype: int64

In [19]:
# look into 'itemstatus'
prices = prices.rename(columns={"itemstatus":"item_in_stock"})

In [20]:
# look into 'itemtype'
prices[prices['itemtype'] == 'not_apply']['chainid'].unique()

array([7290172900007])

In [21]:
prices.groupby("file_id").apply(lambda x:str(x['itemtype'].astype(str).unique())).value_counts()

['1']            187
['1' '0']         35
['0' '1']         25
['not_apply']     10
['0']              8
dtype: int64

In [22]:
use_both_flags = prices.groupby("file_id").apply(lambda x:len(x['itemtype'].unique()))
use_both_flags = use_both_flags[use_both_flags>1].reset_index(name='num_of_item_types')
use_both_flags.file_id#.apply(lambda x:x.split("/")[1]).unique()

# TODO: drop itemtype

0     samples_price/Dor Alon/Price7290492000005-450-...
1     samples_price/Dor Alon/Price7290492000005-450-...
2     samples_price/Dor Alon/Price7290492000005-450-...
3     samples_price/Dor Alon/Price7290492000005-450-...
4     samples_price/Dor Alon/Price7290492000005-450-...
                            ...
56    samples_price/ybitan/Price7290725900003-0033-2...
57    samples_price/ybitan/Price7290725900003-0063-2...
58    samples_price/ybitan/Price7290725900003-0078-2...
59    samples_price/ybitan/Price7290725900003-1252-2...
60    samples_price/ybitan/Price7290725900003-3010-2...
Name: file_id, Length: 61, dtype: object

In [23]:
def collect_details(x):
    return pd.Series([x['itemname'].unique(), x['chainid'].unique()])

itemcode_to_itemname = prices.groupby(['itemcode']).apply(collect_details)
itemcode_to_itemname.columns = ['names','chanin_selling']

In [24]:

itemcode_to_itemname[itemcode_to_itemname['names'].apply(lambda x:len(x)>1)].to_csv("itemcode_as_multiple_name.csv",index=False)

itemcode_to_itemname[itemcode_to_itemname['chanin_selling'].apply(lambda x:len(x) == 1)].to_csv("itemcode_selling_only_once.csv",index=False)

In [25]:
itemname_to_itemcodes = prices.groupby("itemname").apply(lambda x:x.groupby("chainid")['itemcode'].head(1))
itemname_to_itemcodes = itemname_to_itemcodes.reset_index(name="chainid").set_index("itemname").rename(columns={"level_1":"itemcode"})
itemname_to_itemcodes

In [ ]:
itemname_to_itemcodes_maping = itemname_to_itemcodes.reset_index()
itemname_to_itemcodes_maping

,itemname,itemcode,chainid
0,קוטג`3% מועשר 250 גר`,78037,7290010945146
1,קוטג`5% מועשר 250 גר`,78035,7290002868996
2,קוטג`5% מועשר 250 גר`.,78138,7290114310918
3,קוטג`וחצי 5% 375 גר,78093,7290102397679
4,"""אורביטול מי פה 500 מ",9860,7290005423505
...,...,...,...
31994,תשיעיית סקוטש ברייט ירוק לקירצוף,63820,7290012046193
31995,"תשלום על רבע שעה חניה שפע ברכת השם בני ברק 10 ש""ח",12673,365422
31996,"תשלום על שעה חניה שפע ברכת השם בני ברק 35 ש""ח",12672,365421
31997,תשע גלילי סלוטייפ סמיילי,17838,7290108195217
31998,"‏כרוב לבן 1 ק""ג - כ.טרי",14892,7290003996971

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(analyzer='word', ngram_range=(1, 3), min_df=0)
tfidf_matrix = tf.fit_transform(itemname_to_itemcodes_maping['itemname_processed'])

In [102]:
tfidf_matrix[0]

(1, 121985)

In [110]:
# edges = list(zip(framed_matchs['product_1'], framed_matchs['product_2']))
# weighted_edges = list(zip(framed_matchs['product_1'], framed_matchs['product_2'], framed_matchs['score']))

# nodes = list(set(framed_matchs['product_1']).union(set(framed_matchs['product_2'])))

TypeError: 'list' object is not callable

In [45]:
# import networkx as nx
# G = nx.Graph()
# G.add_nodes_from(nodes)
# G.add_edges_from(edges)
# G.add_weighted_edges_from(weighted_edges)

In [46]:
# import community
# partition = community.best_partition(G)
# modularity = community.modularity(partition, G)

In [58]:
# itemname_to_itemcodes_maping['partition'] = [partition[" @ ".join(itemname_to_itemcodes_maping[['itemname','chainid']].iloc[m1].values)] for m1 in range(itemname_to_itemcodes_maping.shape[0])]

In [81]:
# all_chains = itemname_to_itemcodes_maping['chainid'].unique()
# all_chains

array(['7290010945146', '7290002868996', '7290114310918', ..., '365421',
       '7290108195217', '7290003996971'], dtype=object)

In [99]:
# results = []
# for group in itemname_to_itemcodes_maping.groupby('partition'):
#     results.append(group[1]['itemname'].values)

In [100]:
# with open('clusters.txt', 'w') as f:
#     for _list in results:
#         for _string in _list:
#             #f.seek(0)
#             f.write(str(_string) + ',')
#         f.write('\n')

In [98]:
len(results)

15258

In [66]:
_itemname_to_itemcodes = itemname_to_itemcodes.reset_index(name="test")
_itemname_to_itemcodes[_itemname_to_itemcodes['itemname'] == "תפוז"]

TypeError: reset_index() got an unexpected keyword argument 'name'

In [ ]:
prices[prices["itemname"] == 'מלון'].groupby(['chainid'])['itemcode'].unique()

chainid
7290055700014             [1518]
7290058134977              [407]
7290058159628              [178]
7290058173198            [10219]
7290058198450              [232]
7290785400000               [30]
7291059100008    [7290000000078]
Name: itemcode, dtype: object

In [ ]:
lis